site_name: pypas
site_url: https://pypas.es/docs/
site_description: Documentación sobre pypas
site_author: Sergio Delgado Quintero

theme:
  name: mkdocs
  user_color_mode_toggle: true
  locale: es
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: sdelquin
      repo: pypas-cli
hooks:
  - hooks.py

copyright: Copyright &copy; Sergio Delgado Quintero<br>sdelquin@gmail.com
