site_name: pypas
site_url: https://pypas.es/docs/
site_description: Documentación sobre pypas
site_author: Sergio Delgado Quintero

theme:
  name: mkdocs
  user_color_mode_toggle: true
  locale: es
  color_mode: dark
  favicon: static/images/favicon.ico
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: sdelquin
      repo: pypas-cli
extra_css:
  - static/css/custom.css
extra_javascript:
  - static/js/custom.js
plugins:
  - minify:
      cache_safe: true
      css_files:
        - static/css/custom.css
      js_files:
        - static/js/custom.js

copyright: Copyright &copy; Sergio Delgado Quintero<br>sdelquin@gmail.com
